### ISSUE TITLE
Sub-User Story: A User can Vote Questions

### ISSUE THREAD

**Issue by MarwaKhalid** [KingZiad/SOEN-341#61]
Sub-User Story:
-------------
As a user, I want to be able to vote on questions so I can view the best asked question.

Sub-tasks:
---------------
- [ ]  Design the page so the Questions show with an interactive voting button #39 
- [ ] Create/Log in to an Account to Post Question #46
- [ ] Set up a database so that the voting will be saved on the backend. #39
- [ ] PHP: make a file(s) which connects database to CRUD (create/read/update/delete) questions
- [ ] JavaScript files: detect specific events, and perform calls to the backend (PHP files)

Click to confirm which tasks are completed

Deadline: 
-----------
Dec 2

Points:
-----------
Risk Level: Low
Priority Level: Low
Story Points: 2

Acceptance Criteria:
----------------------
- [ ]  GIVEN the user attempts to vote a question WHEN they've already voted THEN the vote should be removed.

| Step | Test Steps | Notes |
| ------|   ----------| --- |
| 1 |  Go to Website | Website is active |
| 2 | Sign in to account | Username and Password match |
| 3 | Access the question | Redirects to Question Page | 
| 4 | User clicks on button to vote on question | Vote can be changed, or removed entirely |
| 5 | Vote count is increased | Vote number update is displayed on screen next to the
